import type { Metadata } from "next";
import { Oswald, Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";


const oswald = Oswald({
  subsets: ["latin"],
  weight: ["200","300","400","500","600","700"],
  variable: "--font-oswald"
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["200","300","400","500","600","700"],
  variable: "--font-inter"
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={`${oswald.variable} ${inter.variable}`}>
      <div className="navbar">
        <div className="navbar-image">
        <Image
          src="/basketball.png"
          alt="Basketball logo"
          width={80}
          height={80}
          priority
        />
        </div>
       
        <div className="navbar-links">
          <Link href={"/"}>Home</Link>
          <Link href={"/seasons"}>Seasons</Link>
          <Link href={"/countries"}>Countries</Link>
          <Link href={"/leagues"}>Leagues</Link>
          <Link href={"/teams"}>Teams</Link>
          <Link href={"/players"}>Players</Link>
        </div>
      </div>
        {children}
      </body>
    </html>
  );
}
